version: '3'

services:
    brevets:
      build: brevets/.
      command: flask_brevets.py
      ports: 
        - "5001:5000"
      depends_on:
        - brevetsdb
      environment:
          DB_HOSTNAME: db
    db:
      image: mongo:5.0.5
